services:
  whatever:
    build: .
    ports:
      - "1477:1477"
    volumes:
      - ./ephemeral:/app
      - ./persistent:/app/persistent:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
    working_dir: /app
    command: npm run dev
